CREATE DATABASE IF NOT EXISTS redViper;
CREATE USER IF NOT EXISTS 'redViper'@'localhost' IDENTIFIED BY 'redViper';
GRANT ALL PRIVILEGES ON redViper.* TO 'redViper'@'localhost';

CREATE TABLE IF NOT EXISTS redViper.zombies ( db_id INT AUTO_INCREMENT, zid VARCHAR(255) NOT NULL, subreddit VARCHAR(255) NOT NULL, reddit_account VARCHAR(255) NOT NULL, aes_key VARCHAR(255) NOT NULL, implant_id VARCHAR(255) NOT NULL, hostname VARCHAR(255) NOT NULL, pub_ip VARCHAR(255) NOT NULL, priv_ip VARCHAR(255) NOT NULL, platform VARCHAR(255) NOT NULL, initial_check TIMESTAMP DEFAULT CURRENT_TIMESTAMP, last_check TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (db_id));

CREATE TABLE IF NOT EXISTS redViper.implants ( db_id INT AUTO_INCREMENT, implant_id VARCHAR(255) NOT NULL, implant_key VARCHAR(255) NOT NULL, reddit_account VARCHAR(255) NOT NULL, subreddit VARCHAR(255) NOT NULL, creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (db_id));
